spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vc-app?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: vc-admin
      maximum-pool-size: 15
      max-lifetime: 850000
      validation-timeout: 1000
      idle-timeout: 60000
      minimum-idle: 5
      connection-test-query: select 1
  jpa:
    open-in-view: false

mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/**/*.xml

#cosid:
#  namespace: ${spring.application.name}
#  segment:
#    enabled: true
#    mode: chain
#    chain:
#      safe-distance: 5
#      prefetch-worker:
#        core-pool-size: 2
#        prefetch-period: 1s
#    distributor:
#      type: redis
#    share:
#      offset: 100
#      step: 10
#      converter:
#        type: to_string
#    provider:
#      admin:
#        offset: 500
#        step: 10
