feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
    connection-timeout: 10000
  client:
    config:
      default:
        loggerLevel: NONE
        connectTimeout: 10000
spring:
  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
